# Replace these with your actual usernames/links
github: [Gitdigital-products] # Up to 4 GitHub usernames
patreon: gitdigital
ko_fi: gitdigital
open_collective: gitdigital-products
custom: ["https://www.paypal.me/yourlink"]

